sudo add-apt-repository ppa:aguignard/ppa -y -u
sudo apt-get install -q \
    arandr\
    autoconf\
    automake\
    build-essential\
    feh\
    git\
    i3blocks\
    i3lock\
    imagemagick\
    libev-dev\
    libpango1.0-dev\
    libstartup-notification0-dev\
    libx11-dev\
    libxcb-cursor-dev\
    libxcb-icccm4-dev\
    libxcb-keysyms1-dev\
    libxcb-randr0-dev\
    libxcb-util0-dev\
    libxcb-xinerama0-dev\
    libxcb-xkb-dev\
    libxcb-xrm-dev\
    libxcb1-dev\
    libxkbcommon-dev\
    libxkbcommon-x11-dev\
    libyajl-dev\
    lm-sensors\
    lxappearance\
    ranger\
    rofi\
    rxvt-unicode-256color\
    scrot\
    unzip\
    vim\
    wget\
    xbacklight\
    xdotool\
